#!/bin/bash
#
#
project_name="LDPUts"
meeting_date="071424"
experiment_name="disclapu"
db_name="071424_LDPUts"
table_name="k400"
extension_code="py"
extension_result="npy"
tool="python -u"

code_dir="/home1/jongminm/${project_name}/experiment/meeting/${meeting_date}/${experiment_name}"
db_dir="/home1/jongminm/${project_name}/experiment/db/${db_name}.db"

#화면에 텍스트 표시:
echo "code_dir = ${code_dir}"

mem_min=2000

k=40
eta=0.015
statistic=elltwo
privmech=disclapu

sample_size_multiplier=1500
n_permutation=999
test_start=1
n_test=200
for privlev in  0.5 1 2 
do
for ii in {1..20..1}
do
    sample_size=$((ii*sample_size_multiplier))

    filename=${experiment_name}_${privmech}${statistic}_n${sample_size}_priv${privlev}
    filename_code=${code_dir}/${filename}.${extension_code}
    filename_job=${code_dir}/${filename}.job
    filename_out=${code_dir}/${filename}.out
    #scalar parameters
    touch ${code_dir}/temp_code
    echo "alphabet_size = ${k}"             >> ${code_dir}/temp_code
    echo "bump_size     = ${eta}"           >> ${code_dir}/temp_code
    echo "privacy_level = ${privlev}"       >> ${code_dir}/temp_code
    echo "sample_size   = ${sample_size}"   >> ${code_dir}/temp_code
    echo "n_permutation = ${n_permutation}" >> ${code_dir}/temp_code
    echo "n_test        = ${n_test}"        >> ${code_dir}/temp_code
    echo "test_start    = ${test_start}"    >> ${code_dir}/temp_code

    #strings
    echo "table_name = '${table_name}'"  >> ${code_dir}/temp_code
    echo "code_dir   = '${code_dir}'"  >> ${code_dir}/temp_code
    echo "priv_mech  = '${privmech}'"  >> ${code_dir}/temp_code
    echo "statistic  = '${statistic}'" >> ${code_dir}/temp_code
    echo "db_dir = '${db_dir}'" >> ${code_dir}/temp_code
    cat ${code_dir}/skeleton_code.${extension_code} >> ${code_dir}/temp_code
    mv ${code_dir}/temp_code ${filename_code}



    # job
    touch ${code_dir}/temp_job
    cat ${code_dir}/skeleton_job.job >> ${code_dir}/temp_job
    mem_cal=$((40*sample_size*k/1024/1024))
    mem=$(echo "if ($mem_min < $mem_cal) $mem_cal else $mem_min" | bc)
    echo "#SBATCH --mem=$((mem))mb" >> ${code_dir}/temp_job
    
    echo "#SBATCH --job-name=${filename}" >> ${code_dir}/temp_job
    echo "#SBATCH --output=${filename_out}" >> ${code_dir}/temp_job
    echo "module purge" >> ${code_dir}/temp_job
    echo "load conda" >> ${code_dir}/temp_job
    cat ${code_dir}/conda_template >> ${code_dir}/temp_job
    echo "${tool}  ${filename_code} > ${filename_out}" >> ${code_dir}/temp_job
    mv ${code_dir}/temp_job ${filename_job}
    sleep 6
    sbatch ${filename_job}
done
done



